### ISSUE TITLE
Add User Authentication

### ISSUE THREAD

**Issue by jason-feng** [dali-lab/flux#1]
@ian-bateman 

Ian why don't you pull this for now and start working on this.

Create a login flow view for restaurants
- email (acts as username)
- password (which is hashed)
- any additional fields you want

Add two different views, one for when you are not authenticated in and it adds you to either login or signup.

The second is where you are already logged in and shows some information (maybe the restaurant list for now since we don't have menus added in yet)

Also part of the signup flow, attach restaurants to users, making sure each user only has one restaurant attached to them. 

You should also differentiate between users that are consumers and restaurant staff

**Comment by ian-bateman** [comment]
Restaurant Authentication and Routing added
